set:
	qjackctl &
	amsynth &

play:	
	python kinect_drumming/kinect_drumming.py c 9
	
play2:
	python kinect_drumming/kinect_drumming.py a 9

play3:
	python kinect_drumming/kinect_drumming.py d# 9

play4:
	python kinect_drumming/kinect_drumming.py g 9

theremin:
	python theremin/digitheremin.py 
	
pitar:
	python pintar/pintar.py
